# Compiler-RT builtins for cross targets
#
# Used by build-multiarch-toolchain.sh Phase 2.
# Parameterized at the cmake command line by:
#   CMAKE_C_COMPILER_TARGET, CMAKE_CXX_COMPILER_TARGET,
#   CMAKE_ASM_COMPILER_TARGET, COMPILER_RT_DEFAULT_TARGET_TRIPLE

set(CMAKE_SYSTEM_NAME Linux CACHE STRING "")
set(CMAKE_BUILD_TYPE Release CACHE STRING "")
set(CMAKE_CROSSCOMPILING ON CACHE BOOL "")
set(CMAKE_C_COMPILER_FORCED ON CACHE BOOL "")
set(CMAKE_CXX_COMPILER_FORCED ON CACHE BOOL "")
set(COMPILER_RT_BUILD_BUILTINS ON CACHE BOOL "")
set(COMPILER_RT_BUILD_CRT ON CACHE BOOL "")
set(COMPILER_RT_BUILD_SANITIZERS OFF CACHE BOOL "")
set(COMPILER_RT_BUILD_XRAY OFF CACHE BOOL "")
set(COMPILER_RT_BUILD_LIBFUZZER OFF CACHE BOOL "")
set(COMPILER_RT_BUILD_PROFILE OFF CACHE BOOL "")
set(COMPILER_RT_BUILD_MEMPROF OFF CACHE BOOL "")
set(COMPILER_RT_BUILD_ORC OFF CACHE BOOL "")
set(COMPILER_RT_BUILD_GWP_ASAN OFF CACHE BOOL "")
set(COMPILER_RT_DEFAULT_TARGET_ONLY ON CACHE BOOL "")
set(LLVM_ENABLE_PER_TARGET_RUNTIME_DIR ON CACHE BOOL "")
